"""
WorkVision AI Database Package.
"""

from workvision_db.base import Base
from workvision_db.session import (
    async_session_factory,
    engine,
    get_async_db,
)
from workvision_db.models import (
    ActivityEvent,
    AttendanceEvent,
    AttendanceType,
    AttendanceTypeEnum,
    AuditLog,
    Building,
    BusinessState,
    BusinessStateEnum,
    Camera,
    CameraTopology,
    DailyWorkSummary,
    Department,
    Employee,
    EventOverride,
    Floor,
    IdentityAssociation,
    IdentityStatus,
    IdentityStatusEnum,
    LocationEvent,
    ObservedActivity,
    ObservedActivityEnum,
    Room,
    StateEvent,
    TrackingSession,
    WorkSession,
    Workstation,
    Zone,
    ZoneType,
    ZoneTypeEnum,
)

__all__ = [
    "Base",
    "engine",
    "async_session_factory",
    "get_async_db",
    # Models & Enums
    "Department",
    "Employee",
    "Building",
    "Floor",
    "Room",
    "Camera",
    "Zone",
    "Workstation",
    "CameraTopology",
    "TrackingSession",
    "IdentityAssociation",
    "LocationEvent",
    "ActivityEvent",
    "StateEvent",
    "AttendanceEvent",
    "WorkSession",
    "DailyWorkSummary",
    "EventOverride",
    "AuditLog",
    "IdentityStatus",
    "IdentityStatusEnum",
    "ObservedActivity",
    "ObservedActivityEnum",
    "BusinessState",
    "BusinessStateEnum",
    "AttendanceType",
    "AttendanceTypeEnum",
    "ZoneType",
    "ZoneTypeEnum",
]
